name = "shikoku-sns-map"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

compatibility_flags = [ "nodejs_compat" ]

[env.production]
compatibility_flags = [ "nodejs_compat" ]